/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PresentIdRouteImport } from './routes/present.$id'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiXaiOauthCallbackRouteImport } from './routes/api/xai/oauth/callback'
import { Route as ApiXaiOauthStartRouteImport } from './routes/api/xai/oauth/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdRoute = PresentIdRouteImport.update({
  id: '/present/$id',
  path: '/present/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXaiOauthCallbackRoute = ApiXaiOauthCallbackRouteImport.update({
  id: '/api/xai/oauth/callback',
  path: '/api/xai/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXaiOauthStartRoute = ApiXaiOauthStartRouteImport.update({
  id: '/api/xai/oauth/start',
  path: '/api/xai/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/present/$id': typeof PresentIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/share/$id': typeof ShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/xai/oauth/callback': typeof ApiXaiOauthCallbackRoute
  '/api/xai/oauth/start': typeof ApiXaiOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/present/$id': typeof PresentIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/share/$id': typeof ShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/xai/oauth/callback': typeof ApiXaiOauthCallbackRoute
  '/api/xai/oauth/start': typeof ApiXaiOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/present/$id': typeof PresentIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/share/$id': typeof ShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/xai/oauth/callback': typeof ApiXaiOauthCallbackRoute
  '/api/xai/oauth/start': typeof ApiXaiOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/present/$id'
    | '/project/$id'
    | '/share/$id'
    | '/api/auth/$'
    | '/api/xai/oauth/callback'
    | '/api/xai/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/present/$id'
    | '/project/$id'
    | '/share/$id'
    | '/api/auth/$'
    | '/api/xai/oauth/callback'
    | '/api/xai/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/present/$id'
    | '/project/$id'
    | '/share/$id'
    | '/api/auth/$'
    | '/api/xai/oauth/callback'
    | '/api/xai/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PresentIdRoute: typeof PresentIdRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ShareIdRoute: typeof ShareIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiXaiOauthCallbackRoute: typeof ApiXaiOauthCallbackRoute
  ApiXaiOauthStartRoute: typeof ApiXaiOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id': {
      id: '/present/$id'
      path: '/present/$id'
      fullPath: '/present/$id'
      preLoaderRoute: typeof PresentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xai/oauth/callback': {
      id: '/api/xai/oauth/callback'
      path: '/api/xai/oauth/callback'
      fullPath: '/api/xai/oauth/callback'
      preLoaderRoute: typeof ApiXaiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xai/oauth/start': {
      id: '/api/xai/oauth/start'
      path: '/api/xai/oauth/start'
      fullPath: '/api/xai/oauth/start'
      preLoaderRoute: typeof ApiXaiOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PresentIdRoute: PresentIdRoute,
  ProjectIdRoute: ProjectIdRoute,
  ShareIdRoute: ShareIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiXaiOauthCallbackRoute: ApiXaiOauthCallbackRoute,
  ApiXaiOauthStartRoute: ApiXaiOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
